# Generated by Django 4.2.27 on 2026-02-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='tenant',
        ),
    ]
